
version: "3.7"

services:  
  app_dev:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    networks:
      audio_text_backend_audio_text_bridge:
        ipv4_address: 169.254.9.3
        aliases:
          - "audio-text-frontend-dev.app"
    ports:
      - 3202:3202  
    volumes:
      - ./:/app/
      - /tmp/uploads/:/app/tmp/uploads/
      - /tmp/transcriptions/:/app/tmp/transcriptions/
      - /app/node_modules

  nginx:
    image: nginx:latest
    networks:
      audio_text_backend_audio_text_bridge:
        ipv4_address: 169.254.9.4
        aliases:
          - "audio-text-nginx.app"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./resources/nginx_dev_ssl.conf:/etc/nginx/conf.d/ssl.conf
      - ./resources/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./resources/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./resources/dhparam.pem:/etc/ssl/certs/dhparam.pem
    depends_on:
      - app_dev

networks:
  audio_text_backend_audio_text_bridge:
    external: true