services:  
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    networks:
      audio_text_backend_audio_text_bridge:
        ipv4_address: 169.254.9.7
        aliases:
          - "audio-text-frontend.app"
    ports:
      - 3202:3202  
    volumes:
      - ./:/app/
      - /app/node_modules
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    networks:
      audio_text_backend_audio_text_bridge:
        ipv4_address: 169.254.9.8
        aliases:
          - "audio-text-nginx.app"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx/ssl/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./nginx/ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem
    depends_on:
      - app

networks:
  audio_text_backend_audio_text_bridge:
    external: true